### PR TITLE
Remove unnecessary Accept header

### PR DESCRIPTION
**Pull request by foolip**
Fixes https://github.com/web-platform-tests/wpt-pr-bot/issues/107.

### CODE REVIEW

**Review by Ms2ger — DISMISSED** [review]

**Comment by foolip** [comment]
Oh, this will require updating tests, which will require understanding how they even work!

**Comment by jcscottiii** [comment]
I fixed the tests. This is passing now.

**Review by past — APPROVED** [review]
Thanks for updating a bajillion tests!

**Comment by foolip** [comment]
Thanks indeed @jcscottiii!

**Pull request merged**
