### PR TITLE
Add Loirooriol as a CSS editor

### PR DESCRIPTION
**Pull request by Loirooriol**
I'm an editor of these CSS specs:
 - https://drafts.csswg.org/css-grid-1/
 - https://drafts.csswg.org/resize-observer-1/

So I shouldn't need reviews to land PRs like this one: https://github.com/web-platform-tests/wpt/pull/36234

### CODE REVIEW

**Comment by Loirooriol** [comment]
I don't know if it's fine like this, or if I should restrict it to the paths of the specs I'm an editor of.

Also not sure who can review, maybe @foolip?

**Comment by Loirooriol** [comment]
Can you review, @Ms2ger ?

**Review by Ms2ger — APPROVED** [review]

**Comment by jcscottiii** [comment]
@Ms2ger You're right. I will deploy this after merging

**Comment by Ms2ger** [comment]
Thanks!

**Comment by jcscottiii** [comment]
The deployment is finished! Thanks for the contribution @Loirooriol !

**Comment by Loirooriol** [comment]
Thanks! https://github.com/web-platform-tests/wpt/pull/36234 still says that I need a review, do I need to wait more?

**Comment by jcscottiii** [comment]
I checked the logs for the webhook. Looked like it should've worked. 
```
DEFAULT 2023-07-25T14:17:15.823627Z [protoPayload.method: POST] [protoPayload.status: 200] [protoPayload.responseSize: 248 B] [protoPayload.latency: 11 ms] [protoPayload.userAgent: GitHub-Hookshot 328e986] /github-hook
DEFAULT 2023-07-25T14:17:15.835Z {"hostname":"localhost", "level":30, "msg":"#36234: handling action 'synchronize'", "name":"wpt-pr-bot", "pid":11, "v":0}
DEFAULT 2023-07-25T14:17:21.200838Z (node:11) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
DEFAULT 2023-07-25T14:17:21.200866Z (Use `node --trace-deprecation ...` to show where the warning was created)
DEFAULT 2023-07-25T14:17:24.240Z {"hostname":"localhost", "level":30, "metadata":{…}, "msg":"#36234: Retrieved metadata for pull request", "name":"wpt-pr-bot", "pid":11, "v":0}
DEFAULT 2023-07-25T14:17:24.348Z {"hostname":"localhost", "level":30, "msg":"#36234: Added missing LABELS if any.", "name":"wpt-pr-bot", "pid":11, "v":0}
DEFAULT 2023-07-25T14:17:24.349Z {"hostname":"localhost", "level":30, "msg":"#36234: Added missing REVIEWERS if any.", "name":"wpt-pr-bot", "pid":11, "v":0}

```

Also the logs on the github side:

```
Request URL: https://wpt-pr-bot.appspot.com/github-hook
Request method: POST
Accept: */*
content-type: application/json
User-Agent: GitHub-Hookshot/328e986
X-GitHub-Delivery: f407cc90-2af5-11ee-8914-2fb60ceacbd7
X-GitHub-Event: pull_request
X-GitHub-Hook-ID: 161784539
X-GitHub-Hook-Installation-Target-ID: 3618133
X-GitHub-Hook-Installation-Target-Type: repository
X-Hub-Signature: sha1=fda9f79f5bd194fc2f9b690cfa10fda9f58a2405
X-Hub-Signature-256: sha256=8677c5ec200d788bb9541b4dc98319fb9a2e953ea8b88d952e56f223d02c161a
```

**Comment by jcscottiii** [comment]
Could you push your changes to another branch and open a second PR? I just want to check something out

**Comment by Loirooriol** [comment]
Sure, I opened https://github.com/web-platform-tests/wpt/pull/41173

**Comment by Loirooriol** [comment]
@jcscottiii Have you been able to check the problem?

**Comment by jcscottiii** [comment]
Taking a look now

**Comment by jcscottiii** [comment]
Raw notes for myself.



This process kicks off:

1. When an event is received. It needs to be a pull request that is not closed or in draft mode
  - https://github.com/web-platform-tests/wpt-pr-bot/blob/d930685743c9cec2ad0d1080b70acaa47a333800/index.js#L57-L62
  - https://github.com/web-platform-tests/wpt-pr-bot/blob/d930685743c9cec2ad0d1080b70acaa47a333800/lib/filter.js#L7-L21
  - https://github.com/web-platform-tests/wpt-pr-bot/blob/d930685743c9cec2ad0d1080b70acaa47a333800/lib/filter.js#L23-L37
2. The pull request event is then even further filtered to only continue on one of these event types:
  - https://github.com/web-platform-tests/wpt-pr-bot/blob/d930685743c9cec2ad0d1080b70acaa47a333800/index.js#L70-L71
3. Explanations for each
  - [opened](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=opened#pull_request) - `A pull request was created`
  - [closed](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=closed#pull_request) - `A pull request was closed. If merged is false in the webhook payload, the pull request was closed with unmerged commits. If merged is true in the webhook payload, the pull request was merged.`
  - [synchronize](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=synchronize#pull_request) ([additional notes](https://github.com/orgs/community/discussions/24567)) - `A pull request's head branch was updated. For example, the head branch was updated from the base branch or new commits were pushed to the head branch.`
4. Then the metadata is retrieved for the pull request
  - https://github.com/web-platform-tests/wpt-pr-bot/blob/d930685743c9cec2ad0d1080b70acaa47a333800/index.js#L80
5. In the metadata retrieval, the author names are standardized to lower case
  - https://github.com/web-platform-tests/wpt-pr-bot/blob/d930685743c9cec2ad0d1080b70acaa47a333800/lib/metadata/index.js#L44-L50 
6. That author variable is later stored in the login variable
  - https://github.com/web-platform-tests/wpt-pr-bot/blob/d930685743c9cec2ad0d1080b70acaa47a333800/lib/metadata/index.js#L83
 7. The login will be lower case but the csseditors will be captialized
   - https://github.com/web-platform-tests/wpt-pr-bot/blob/d930685743c9cec2ad0d1080b70acaa47a333800/lib/comment.js#L9-L13


That's the problem. We need to lowercase your username

**Comment by Loirooriol** [comment]
Thanks for the investigation!

**Comment by jcscottiii** [comment]
@Loirooriol the fix has been deployed. Could you try again? (You may need to create a new PR entirely again)

**Comment by Loirooriol** [comment]
A force-push sufficed, thanks! https://github.com/web-platform-tests/wpt/pull/36234 approved by wpt-pr-bot.

**Pull request merged**
