### PR TITLE
Ignore draft pull requests

### PR DESCRIPTION
**Pull request by Hexcles**
How do I test this? It seems like we don't have existing tests for the filtering logic?

also cc @LukeZielinski

### CODE REVIEW

**Comment by jugglinmike** [comment]
That's right; no filtering tests at all. The filtering isn't very easily tested, either since the server unconditionally responds to all requests. Getting it under test will require a significant time investment. I'm comfortable accepting the status quo to get this patch merged, though I will probably follow up with a few logging statements.

One question though: do you know if an event is emitted when a draft pull request is changed into a "true" pull request? Ideally, the script could observe that such pull requests are assigned/labeled at that moment.

**Comment by Hexcles** [comment]
> One question though: do you know if an event is emitted when a draft pull request is changed into a "true" pull request? Ideally, the script could observe that such pull requests are assigned/labeled at that moment.

I think (and certainly hope) that's the case, but can't find clear answers from the docs. Perhaps we can try (if deploying the bot, and potentially rolling it back, isn't too difficult)?

**Comment by LukeZielinski** [comment]
Thanks for doing this!

**Comment by jugglinmike** [comment]
Thanks, @Hexcles!

**Pull request merged**
