### PR TITLE
Stop inviting people as web-platform-tests/wpt collaborators

### PR DESCRIPTION
**Pull request by foolip**
Part of https://github.com/web-platform-tests/wpt-pr-bot/issues/21.

### CODE REVIEW

**Comment by foolip** [comment]
It's only if a pending invitation is treated differently than no invitation at all that this could make a difference. I have the same level of access as wpt-pr-bot, so I tried assigning someone (rubys) with a pending invitation on a review in the wpt repo, and it doesn't work.

If you believe this will break something, what should I change? I'd like to stop the flow of invites to the repo ASAP.

**Comment by foolip** [comment]
Sigh. As it turns out this *did* break reviewers being added by wpt-pr-bot, but I don't understand why.

**Comment by foolip** [comment]
I am a bit confused. Worked fine on https://github.com/web-platform-tests/wpt/pull/11247, so I'm not sure if there are cases where it doesn't work.

@tobie, can any errors logged be seen anywhere?

**Comment by tobie** [comment]
What you want to do is return “none” in the case where reviewers don’t have collaborator status (instead of “read” as you did) and then filter the owners array before POSTing it to the endpoint.

**Comment by foolip** [comment]
Implemented that in https://github.com/web-platform-tests/wpt-pr-bot/pull/23.

**Pull request merged**
